"""
Extraction Pipeline
───────────────────
Parses the PDF file and extracts:
  • Raw text per page
  • Images per page → captions generated by GPT-4o-mini (vision)

Output: one JSON file per page saved to  data/extracted/page_NNN.json
"""

import base64
import json
import sys
import time
from pathlib import Path

import fitz  # PyMuPDF
from openai import OpenAI

from config import (
    EXTRACTED_DIR,
    LLM_MODEL,
    MIN_IMAGE_SIZE,
    OPENAI_API_KEY,
    PDF_PATH,
)

client = OpenAI(api_key=OPENAI_API_KEY)


# ── helpers ──────────────────────────────────────────────────────────────────


def _caption_image(image_bytes: bytes, page_number: int, img_index: int) -> str:
    """Send an image to GPT-4o-mini vision and return a short caption."""
    b64 = base64.b64encode(image_bytes).decode("utf-8")
    try:
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a helpful assistant that describes images from "
                        "a biosciences quality-assurance textbook. "
                        "Provide a concise, informative caption (1-3 sentences) "
                        "that captures the key information shown in the figure."
                    ),
                },
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": (
                                f"Describe this figure from page {page_number} "
                                f"(image #{img_index + 1}) of a QA/regulatory affairs textbook."
                            ),
                        },
                        {
                            "type": "image_url",
                            "image_url": {
                                "url": f"data:image/png;base64,{b64}",
                                "detail": "low",
                            },
                        },
                    ],
                },
            ],
            max_tokens=200,
            temperature=0.3,
        )
        return response.choices[0].message.content.strip()
    except Exception as exc:
        print(f"Caption failed for page {page_number} img {img_index}: {exc}")
        return f"[Image on page {page_number}]"


def _extract_page(doc: fitz.Document, page_index: int) -> dict:
    """Extract text and image captions from a single PDF page."""
    page = doc[page_index]
    page_number = page_index + 1  # 1-based

    # Text
    text = page.get_text("text").strip()

    # Images
    image_captions: list[str] = []
    image_list = page.get_images(full=True)
    for img_index, img_info in enumerate(image_list):
        xref = img_info[0]
        try:
            base_image = doc.extract_image(xref)
            image_bytes = base_image["image"]
            if len(image_bytes) < MIN_IMAGE_SIZE:
                continue  # skip tiny icons / decorations
            caption = _caption_image(image_bytes, page_number, img_index)
            image_captions.append(caption)
        except Exception as exc:
            print(f" Image extraction failed page {page_number} img {img_index}: {exc}")

    return {
        "page_number": page_number,
        "text": text,
        "image_captions": image_captions,
    }


# ── main ─────────────────────────────────────────────────────────────────────


def run_extraction() -> None:
    """Run the full PDF extraction pipeline."""
    if not PDF_PATH.exists():
        print(f"PDF not found at {PDF_PATH}")
        sys.exit(1)

    EXTRACTED_DIR.mkdir(parents=True, exist_ok=True)

    doc = fitz.open(str(PDF_PATH))
    total_pages = len(doc)
    print(f"Opened PDF: {PDF_PATH.name}  ({total_pages} pages)")

    for idx in range(total_pages):
        page_number = idx + 1
        print(f"  → Extracting page {page_number}/{total_pages} …", end="", flush=True)
        start = time.time()

        page_data = _extract_page(doc, idx)

        out_path = EXTRACTED_DIR / f"page_{page_number:03d}.json"
        with open(out_path, "w", encoding="utf-8") as fp:
            json.dump(page_data, fp, ensure_ascii=False, indent=2)

        elapsed = time.time() - start
        n_imgs = len(page_data["image_captions"])
        print(f"  done ({elapsed:.1f}s, {n_imgs} image(s) captioned)")

    doc.close()
    print(f"\n Extraction complete → {EXTRACTED_DIR}")


if __name__ == "__main__":
    run_extraction()
